# Generated by Django 4.1.2 on 2023-02-04 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CourseInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CourseNumber", models.CharField(default="", max_length=4)),
                ("CourseTitle", models.CharField(default="", max_length=4)),
            ],
        ),
    ]
